namespace DiscoverGists.Helpers.Icon
{
    public class FontAwesomeBrands
    {
        public static string AccessibleIcon { get { return "\uf368"; } }
        public static string Accusoft { get { return "\uf369"; } }
        public static string Adn { get { return "\uf170"; } }
        public static string Adversal { get { return "\uf36a"; } }
        public static string Affiliatetheme { get { return "\uf36b"; } }
        public static string Algolia { get { return "\uf36c"; } }
        public static string AmazonPay { get { return "\uf42c"; } }
        public static string Amazon { get { return "\uf270"; } }
        public static string Amilia { get { return "\uf36d"; } }
        public static string Android { get { return "\uf17b"; } }
        public static string Angellist { get { return "\uf209"; } }
        public static string Angrycreative { get { return "\uf36e"; } }
        public static string Angular { get { return "\uf420"; } }
        public static string AppStoreIos { get { return "\uf370"; } }
        public static string AppStore { get { return "\uf36f"; } }
        public static string Apper { get { return "\uf371"; } }
        public static string ApplePay { get { return "\uf415"; } }
        public static string Apple { get { return "\uf179"; } }
        public static string Asymmetrik { get { return "\uf372"; } }
        public static string Audible { get { return "\uf373"; } }
        public static string Autoprefixer { get { return "\uf41c"; } }
        public static string Avianex { get { return "\uf374"; } }
        public static string Aviato { get { return "\uf421"; } }
        public static string Aws { get { return "\uf375"; } }
        public static string Bandcamp { get { return "\uf2d5"; } }
        public static string BehanceSquare { get { return "\uf1b5"; } }
        public static string Behance { get { return "\uf1b4"; } }
        public static string Bimobject { get { return "\uf378"; } }
        public static string Bitbucket { get { return "\uf171"; } }
        public static string Bitcoin { get { return "\uf379"; } }
        public static string Bity { get { return "\uf37a"; } }
        public static string BlackTie { get { return "\uf27e"; } }
        public static string Blackberry { get { return "\uf37b"; } }
        public static string BloggerB { get { return "\uf37d"; } }
        public static string Blogger { get { return "\uf37c"; } }
        public static string BluetoothB { get { return "\uf294"; } }
        public static string Bluetooth { get { return "\uf293"; } }
        public static string Btc { get { return "\uf15a"; } }
        public static string Buromobelexperte { get { return "\uf37f"; } }
        public static string Buysellads { get { return "\uf20d"; } }
        public static string CcAmazonPay { get { return "\uf42d"; } }
        public static string CcAmex { get { return "\uf1f3"; } }
        public static string CcApplePay { get { return "\uf416"; } }
        public static string CcDinersClub { get { return "\uf24c"; } }
        public static string CcDiscover { get { return "\uf1f2"; } }
        public static string CcJcb { get { return "\uf24b"; } }
        public static string CcMastercard { get { return "\uf1f1"; } }
        public static string CcPaypal { get { return "\uf1f4"; } }
        public static string CcStripe { get { return "\uf1f5"; } }
        public static string CcVisa { get { return "\uf1f0"; } }
        public static string Centercode { get { return "\uf380"; } }
        public static string Chrome { get { return "\uf268"; } }
        public static string Cloudscale { get { return "\uf383"; } }
        public static string Cloudsmith { get { return "\uf384"; } }
        public static string Cloudversify { get { return "\uf385"; } }
        public static string Codepen { get { return "\uf1cb"; } }
        public static string Codiepie { get { return "\uf284"; } }
        public static string Connectdevelop { get { return "\uf20e"; } }
        public static string Contao { get { return "\uf26d"; } }
        public static string Cpanel { get { return "\uf388"; } }
        public static string CreativeCommonsBy { get { return "\uf4e7"; } }
        public static string CreativeCommonsNcEu { get { return "\uf4e9"; } }
        public static string CreativeCommonsNcJp { get { return "\uf4ea"; } }
        public static string CreativeCommonsNc { get { return "\uf4e8"; } }
        public static string CreativeCommonsNd { get { return "\uf4eb"; } }
        public static string CreativeCommonsPdAlt { get { return "\uf4ed"; } }
        public static string CreativeCommonsPd { get { return "\uf4ec"; } }
        public static string CreativeCommonsRemix { get { return "\uf4ee"; } }
        public static string CreativeCommonsSa { get { return "\uf4ef"; } }
        public static string CreativeCommonsSamplingPlus { get { return "\uf4f1"; } }
        public static string CreativeCommonsSampling { get { return "\uf4f0"; } }
        public static string CreativeCommonsShare { get { return "\uf4f2"; } }
        public static string CreativeCommons { get { return "\uf25e"; } }
        public static string Css3Alt { get { return "\uf38b"; } }
        public static string Css3 { get { return "\uf13c"; } }
        public static string Cuttlefish { get { return "\uf38c"; } }
        public static string DAndD { get { return "\uf38d"; } }
        public static string Dashcube { get { return "\uf210"; } }
        public static string Delicious { get { return "\uf1a5"; } }
        public static string Deploydog { get { return "\uf38e"; } }
        public static string Deskpro { get { return "\uf38f"; } }
        public static string Deviantart { get { return "\uf1bd"; } }
        public static string Digg { get { return "\uf1a6"; } }
        public static string DigitalOcean { get { return "\uf391"; } }
        public static string Discord { get { return "\uf392"; } }
        public static string Discourse { get { return "\uf393"; } }
        public static string Dochub { get { return "\uf394"; } }
        public static string Docker { get { return "\uf395"; } }
        public static string Draft2digital { get { return "\uf396"; } }
        public static string DribbbleSquare { get { return "\uf397"; } }
        public static string Dribbble { get { return "\uf17d"; } }
        public static string Dropbox { get { return "\uf16b"; } }
        public static string Drupal { get { return "\uf1a9"; } }
        public static string Dyalog { get { return "\uf399"; } }
        public static string Earlybirds { get { return "\uf39a"; } }
        public static string Ebay { get { return "\uf4f4"; } }
        public static string Edge { get { return "\uf282"; } }
        public static string Elementor { get { return "\uf430"; } }
        public static string Ello { get { return "\uf5f1"; } }
        public static string Ember { get { return "\uf423"; } }
        public static string Empire { get { return "\uf1d1"; } }
        public static string Envira { get { return "\uf299"; } }
        public static string Erlang { get { return "\uf39d"; } }
        public static string Ethereum { get { return "\uf42e"; } }
        public static string Etsy { get { return "\uf2d7"; } }
        public static string Expeditedssl { get { return "\uf23e"; } }
        public static string FacebookF { get { return "\uf39e"; } }
        public static string FacebookMessenger { get { return "\uf39f"; } }
        public static string FacebookSquare { get { return "\uf082"; } }
        public static string Facebook { get { return "\uf09a"; } }
        public static string Firefox { get { return "\uf269"; } }
        public static string FirstOrderAlt { get { return "\uf50a"; } }
        public static string FirstOrder { get { return "\uf2b0"; } }
        public static string Firstdraft { get { return "\uf3a1"; } }
        public static string Flickr { get { return "\uf16e"; } }
        public static string Flipboard { get { return "\uf44d"; } }
        public static string Fly { get { return "\uf417"; } }
        public static string FontAwesomeAlt { get { return "\uf35c"; } }
        public static string FontAwesomeFlag { get { return "\uf425"; } }
        public static string FontAwesome { get { return "\uf2b4"; } }
        public static string FonticonsFi { get { return "\uf3a2"; } }
        public static string Fonticons { get { return "\uf280"; } }
        public static string FortAwesomeAlt { get { return "\uf3a3"; } }
        public static string FortAwesome { get { return "\uf286"; } }
        public static string Forumbee { get { return "\uf211"; } }
        public static string Foursquare { get { return "\uf180"; } }
        public static string FreeCodeCamp { get { return "\uf2c5"; } }
        public static string Freebsd { get { return "\uf3a4"; } }
        public static string Fulcrum { get { return "\uf50b"; } }
        public static string GalacticRepublic { get { return "\uf50c"; } }
        public static string GalacticSenate { get { return "\uf50d"; } }
        public static string GetPocket { get { return "\uf265"; } }
        public static string GgCircle { get { return "\uf261"; } }
        public static string Gg { get { return "\uf260"; } }
        public static string GitSquare { get { return "\uf1d2"; } }
        public static string Git { get { return "\uf1d3"; } }
        public static string GithubAlt { get { return "\uf113"; } }
        public static string GithubSquare { get { return "\uf092"; } }
        public static string Github { get { return "\uf09b"; } }
        public static string Gitkraken { get { return "\uf3a6"; } }
        public static string Gitlab { get { return "\uf296"; } }
        public static string Gitter { get { return "\uf426"; } }
        public static string GlideG { get { return "\uf2a6"; } }
        public static string Glide { get { return "\uf2a5"; } }
        public static string Gofore { get { return "\uf3a7"; } }
        public static string GoodreadsG { get { return "\uf3a9"; } }
        public static string Goodreads { get { return "\uf3a8"; } }
        public static string GoogleDrive { get { return "\uf3aa"; } }
        public static string GooglePlay { get { return "\uf3ab"; } }
        public static string GooglePlusG { get { return "\uf0d5"; } }
        public static string GooglePlusSquare { get { return "\uf0d4"; } }
        public static string GooglePlus { get { return "\uf2b3"; } }
        public static string GoogleWallet { get { return "\uf1ee"; } }
        public static string Google { get { return "\uf1a0"; } }
        public static string Gratipay { get { return "\uf184"; } }
        public static string Grav { get { return "\uf2d6"; } }
        public static string Gripfire { get { return "\uf3ac"; } }
        public static string Grunt { get { return "\uf3ad"; } }
        public static string Gulp { get { return "\uf3ae"; } }
        public static string HackerNewsSquare { get { return "\uf3af"; } }
        public static string HackerNews { get { return "\uf1d4"; } }
        public static string Hackerrank { get { return "\uf5f7"; } }
        public static string Hips { get { return "\uf452"; } }
        public static string HireAHelper { get { return "\uf3b0"; } }
        public static string Hooli { get { return "\uf427"; } }
        public static string Hornbill { get { return "\uf592"; } }
        public static string Hotjar { get { return "\uf3b1"; } }
        public static string Houzz { get { return "\uf27c"; } }
        public static string Html5 { get { return "\uf13b"; } }
        public static string Hubspot { get { return "\uf3b2"; } }
        public static string Imdb { get { return "\uf2d8"; } }
        public static string Instagram { get { return "\uf16d"; } }
        public static string InternetExplorer { get { return "\uf26b"; } }
        public static string Ioxhost { get { return "\uf208"; } }
        public static string ItunesNote { get { return "\uf3b5"; } }
        public static string Itunes { get { return "\uf3b4"; } }
        public static string Java { get { return "\uf4e4"; } }
        public static string JediOrder { get { return "\uf50e"; } }
        public static string Jenkins { get { return "\uf3b6"; } }
        public static string Joget { get { return "\uf3b7"; } }
        public static string Joomla { get { return "\uf1aa"; } }
        public static string JsSquare { get { return "\uf3b9"; } }
        public static string Js { get { return "\uf3b8"; } }
        public static string Jsfiddle { get { return "\uf1cc"; } }
        public static string Kaggle { get { return "\uf5fa"; } }
        public static string Keybase { get { return "\uf4f5"; } }
        public static string Keycdn { get { return "\uf3ba"; } }
        public static string KickstarterK { get { return "\uf3bc"; } }
        public static string Kickstarter { get { return "\uf3bb"; } }
        public static string Korvue { get { return "\uf42f"; } }
        public static string Laravel { get { return "\uf3bd"; } }
        public static string LastfmSquare { get { return "\uf203"; } }
        public static string Lastfm { get { return "\uf202"; } }
        public static string Leanpub { get { return "\uf212"; } }
        public static string Less { get { return "\uf41d"; } }
        public static string Line { get { return "\uf3c0"; } }
        public static string LinkedinIn { get { return "\uf0e1"; } }
        public static string Linkedin { get { return "\uf08c"; } }
        public static string Linode { get { return "\uf2b8"; } }
        public static string Linux { get { return "\uf17c"; } }
        public static string Lyft { get { return "\uf3c3"; } }
        public static string Magento { get { return "\uf3c4"; } }
        public static string Mailchimp { get { return "\uf59e"; } }
        public static string Mandalorian { get { return "\uf50f"; } }
        public static string Markdown { get { return "\uf60f"; } }
        public static string Mastodon { get { return "\uf4f6"; } }
        public static string Maxcdn { get { return "\uf136"; } }
        public static string Medapps { get { return "\uf3c6"; } }
        public static string MediumM { get { return "\uf3c7"; } }
        public static string Medium { get { return "\uf23a"; } }
        public static string Medrt { get { return "\uf3c8"; } }
        public static string Meetup { get { return "\uf2e0"; } }
        public static string Megaport { get { return "\uf5a3"; } }
        public static string Microsoft { get { return "\uf3ca"; } }
        public static string Mix { get { return "\uf3cb"; } }
        public static string Mixcloud { get { return "\uf289"; } }
        public static string Mizuni { get { return "\uf3cc"; } }
        public static string Modx { get { return "\uf285"; } }
        public static string Monero { get { return "\uf3d0"; } }
        public static string Napster { get { return "\uf3d2"; } }
        public static string Neos { get { return "\uf612"; } }
        public static string Nimblr { get { return "\uf5a8"; } }
        public static string NintendoSwitch { get { return "\uf418"; } }
        public static string NodeJs { get { return "\uf3d3"; } }
        public static string Node { get { return "\uf419"; } }
        public static string Npm { get { return "\uf3d4"; } }
        public static string Ns8 { get { return "\uf3d5"; } }
        public static string Nutritionix { get { return "\uf3d6"; } }
        public static string OdnoklassnikiSquare { get { return "\uf264"; } }
        public static string Odnoklassniki { get { return "\uf263"; } }
        public static string OldRepublic { get { return "\uf510"; } }
        public static string Opencart { get { return "\uf23d"; } }
        public static string Openid { get { return "\uf19b"; } }
        public static string Opera { get { return "\uf26a"; } }
        public static string OptinMonster { get { return "\uf23c"; } }
        public static string Osi { get { return "\uf41a"; } }
        public static string Page4 { get { return "\uf3d7"; } }
        public static string Pagelines { get { return "\uf18c"; } }
        public static string Palfed { get { return "\uf3d8"; } }
        public static string Patreon { get { return "\uf3d9"; } }
        public static string Paypal { get { return "\uf1ed"; } }
        public static string Periscope { get { return "\uf3da"; } }
        public static string Phabricator { get { return "\uf3db"; } }
        public static string PhoenixFramework { get { return "\uf3dc"; } }
        public static string PhoenixSquadron { get { return "\uf511"; } }
        public static string Php { get { return "\uf457"; } }
        public static string PiedPiperAlt { get { return "\uf1a8"; } }
        public static string PiedPiperHat { get { return "\uf4e5"; } }
        public static string PiedPiperPp { get { return "\uf1a7"; } }
        public static string PiedPiper { get { return "\uf2ae"; } }
        public static string PinterestP { get { return "\uf231"; } }
        public static string PinterestSquare { get { return "\uf0d3"; } }
        public static string Pinterest { get { return "\uf0d2"; } }
        public static string Playstation { get { return "\uf3df"; } }
        public static string ProductHunt { get { return "\uf288"; } }
        public static string Pushed { get { return "\uf3e1"; } }
        public static string Python { get { return "\uf3e2"; } }
        public static string Qq { get { return "\uf1d6"; } }
        public static string Quinscape { get { return "\uf459"; } }
        public static string Quora { get { return "\uf2c4"; } }
        public static string RProject { get { return "\uf4f7"; } }
        public static string Ravelry { get { return "\uf2d9"; } }
        public static string React { get { return "\uf41b"; } }
        public static string Readme { get { return "\uf4d5"; } }
        public static string Rebel { get { return "\uf1d0"; } }
        public static string RedRiver { get { return "\uf3e3"; } }
        public static string RedditAlien { get { return "\uf281"; } }
        public static string RedditSquare { get { return "\uf1a2"; } }
        public static string Reddit { get { return "\uf1a1"; } }
        public static string Rendact { get { return "\uf3e4"; } }
        public static string Renren { get { return "\uf18b"; } }
        public static string Replyd { get { return "\uf3e6"; } }
        public static string Researchgate { get { return "\uf4f8"; } }
        public static string Resolving { get { return "\uf3e7"; } }
        public static string Rev { get { return "\uf5b2"; } }
        public static string Rocketchat { get { return "\uf3e8"; } }
        public static string Rockrms { get { return "\uf3e9"; } }
        public static string Safari { get { return "\uf267"; } }
        public static string Sass { get { return "\uf41e"; } }
        public static string Schlix { get { return "\uf3ea"; } }
        public static string Scribd { get { return "\uf28a"; } }
        public static string Searchengin { get { return "\uf3eb"; } }
        public static string Sellcast { get { return "\uf2da"; } }
        public static string Sellsy { get { return "\uf213"; } }
        public static string Servicestack { get { return "\uf3ec"; } }
        public static string Shirtsinbulk { get { return "\uf214"; } }
        public static string Shopware { get { return "\uf5b5"; } }
        public static string Simplybuilt { get { return "\uf215"; } }
        public static string Sistrix { get { return "\uf3ee"; } }
        public static string Sith { get { return "\uf512"; } }
        public static string Skyatlas { get { return "\uf216"; } }
        public static string Skype { get { return "\uf17e"; } }
        public static string SlackHash { get { return "\uf3ef"; } }
        public static string Slack { get { return "\uf198"; } }
        public static string Slideshare { get { return "\uf1e7"; } }
        public static string SnapchatGhost { get { return "\uf2ac"; } }
        public static string SnapchatSquare { get { return "\uf2ad"; } }
        public static string Snapchat { get { return "\uf2ab"; } }
        public static string Soundcloud { get { return "\uf1be"; } }
        public static string Speakap { get { return "\uf3f3"; } }
        public static string Spotify { get { return "\uf1bc"; } }
        public static string Squarespace { get { return "\uf5be"; } }
        public static string StackExchange { get { return "\uf18d"; } }
        public static string StackOverflow { get { return "\uf16c"; } }
        public static string Staylinked { get { return "\uf3f5"; } }
        public static string SteamSquare { get { return "\uf1b7"; } }
        public static string SteamSymbol { get { return "\uf3f6"; } }
        public static string Steam { get { return "\uf1b6"; } }
        public static string StickerMule { get { return "\uf3f7"; } }
        public static string Strava { get { return "\uf428"; } }
        public static string StripeS { get { return "\uf42a"; } }
        public static string Stripe { get { return "\uf429"; } }
        public static string Studiovinari { get { return "\uf3f8"; } }
        public static string StumbleuponCircle { get { return "\uf1a3"; } }
        public static string Stumbleupon { get { return "\uf1a4"; } }
        public static string Superpowers { get { return "\uf2dd"; } }
        public static string Supple { get { return "\uf3f9"; } }
        public static string Teamspeak { get { return "\uf4f9"; } }
        public static string TelegramPlane { get { return "\uf3fe"; } }
        public static string Telegram { get { return "\uf2c6"; } }
        public static string TencentWeibo { get { return "\uf1d5"; } }
        public static string Themeco { get { return "\uf5c6"; } }
        public static string Themeisle { get { return "\uf2b2"; } }
        public static string TradeFederation { get { return "\uf513"; } }
        public static string Trello { get { return "\uf181"; } }
        public static string Tripadvisor { get { return "\uf262"; } }
        public static string TumblrSquare { get { return "\uf174"; } }
        public static string Tumblr { get { return "\uf173"; } }
        public static string Twitch { get { return "\uf1e8"; } }
        public static string TwitterSquare { get { return "\uf081"; } }
        public static string Twitter { get { return "\uf099"; } }
        public static string Typo3 { get { return "\uf42b"; } }
        public static string Uber { get { return "\uf402"; } }
        public static string Uikit { get { return "\uf403"; } }
        public static string Uniregistry { get { return "\uf404"; } }
        public static string Untappd { get { return "\uf405"; } }
        public static string Usb { get { return "\uf287"; } }
        public static string Ussunnah { get { return "\uf407"; } }
        public static string Vaadin { get { return "\uf408"; } }
        public static string Viacoin { get { return "\uf237"; } }
        public static string ViadeoSquare { get { return "\uf2aa"; } }
        public static string Viadeo { get { return "\uf2a9"; } }
        public static string Viber { get { return "\uf409"; } }
        public static string VimeoSquare { get { return "\uf194"; } }
        public static string VimeoV { get { return "\uf27d"; } }
        public static string Vimeo { get { return "\uf40a"; } }
        public static string Vine { get { return "\uf1ca"; } }
        public static string Vk { get { return "\uf189"; } }
        public static string Vnv { get { return "\uf40b"; } }
        public static string Vuejs { get { return "\uf41f"; } }
        public static string Weebly { get { return "\uf5cc"; } }
        public static string Weibo { get { return "\uf18a"; } }
        public static string Weixin { get { return "\uf1d7"; } }
        public static string WhatsappSquare { get { return "\uf40c"; } }
        public static string Whatsapp { get { return "\uf232"; } }
        public static string Whmcs { get { return "\uf40d"; } }
        public static string WikipediaW { get { return "\uf266"; } }
        public static string Windows { get { return "\uf17a"; } }
        public static string Wix { get { return "\uf5cf"; } }
        public static string WolfPackBattalion { get { return "\uf514"; } }
        public static string WordpressSimple { get { return "\uf411"; } }
        public static string Wordpress { get { return "\uf19a"; } }
        public static string Wpbeginner { get { return "\uf297"; } }
        public static string Wpexplorer { get { return "\uf2de"; } }
        public static string Wpforms { get { return "\uf298"; } }
        public static string Xbox { get { return "\uf412"; } }
        public static string XingSquare { get { return "\uf169"; } }
        public static string Xing { get { return "\uf168"; } }
        public static string YCombinator { get { return "\uf23b"; } }
        public static string Yahoo { get { return "\uf19e"; } }
        public static string YandexInternational { get { return "\uf414"; } }
        public static string Yandex { get { return "\uf413"; } }
        public static string Yelp { get { return "\uf1e9"; } }
        public static string Yoast { get { return "\uf2b1"; } }
        public static string YoutubeSquare { get { return "\uf431"; } }
        public static string Youtube { get { return "\uf167"; } }
        public static string Zhihu { get { return "\uf63f"; } }
    }
}
