namespace DiscoverGists.Helpers.Icon
{
    public class FontAwesomeSolid
    {
        public static string GlassMartini { get { return "\uf000"; } }
        public static string Music { get { return "\uf001"; } }
        public static string Search { get { return "\uf002"; } }
        public static string Heart { get { return "\uf004"; } }
        public static string Star { get { return "\uf005"; } }
        public static string User { get { return "\uf007"; } }
        public static string Film { get { return "\uf008"; } }
        public static string ThLarge { get { return "\uf009"; } }
        public static string Th { get { return "\uf00a"; } }
        public static string ThList { get { return "\uf00b"; } }
        public static string Check { get { return "\uf00c"; } }
        public static string Times { get { return "\uf00d"; } }
        public static string SearchPlus { get { return "\uf00e"; } }
        public static string SearchMinus { get { return "\uf010"; } }
        public static string PowerOff { get { return "\uf011"; } }
        public static string Signal { get { return "\uf012"; } }
        public static string Cog { get { return "\uf013"; } }
        public static string Home { get { return "\uf015"; } }
        public static string Clock { get { return "\uf017"; } }
        public static string Road { get { return "\uf018"; } }
        public static string Download { get { return "\uf019"; } }
        public static string Inbox { get { return "\uf01c"; } }
        public static string Redo { get { return "\uf01e"; } }
        public static string Sync { get { return "\uf021"; } }
        public static string ListAlt { get { return "\uf022"; } }
        public static string Lock { get { return "\uf023"; } }
        public static string Flag { get { return "\uf024"; } }
        public static string Headphones { get { return "\uf025"; } }
        public static string VolumeOff { get { return "\uf026"; } }
        public static string VolumeDown { get { return "\uf027"; } }
        public static string VolumeUp { get { return "\uf028"; } }
        public static string Qrcode { get { return "\uf029"; } }
        public static string Barcode { get { return "\uf02a"; } }
        public static string Tag { get { return "\uf02b"; } }
        public static string Tags { get { return "\uf02c"; } }
        public static string Book { get { return "\uf02d"; } }
        public static string Bookmark { get { return "\uf02e"; } }
        public static string Print { get { return "\uf02f"; } }
        public static string Camera { get { return "\uf030"; } }
        public static string Font { get { return "\uf031"; } }
        public static string Bold { get { return "\uf032"; } }
        public static string Italic { get { return "\uf033"; } }
        public static string TextHeight { get { return "\uf034"; } }
        public static string TextWidth { get { return "\uf035"; } }
        public static string AlignLeft { get { return "\uf036"; } }
        public static string AlignCenter { get { return "\uf037"; } }
        public static string AlignRight { get { return "\uf038"; } }
        public static string AlignJustify { get { return "\uf039"; } }
        public static string List { get { return "\uf03a"; } }
        public static string Outdent { get { return "\uf03b"; } }
        public static string Indent { get { return "\uf03c"; } }
        public static string Video { get { return "\uf03d"; } }
        public static string Image { get { return "\uf03e"; } }
        public static string MapMarker { get { return "\uf041"; } }
        public static string Adjust { get { return "\uf042"; } }
        public static string Tint { get { return "\uf043"; } }
        public static string Edit { get { return "\uf044"; } }
        public static string StepBackward { get { return "\uf048"; } }
        public static string FastBackward { get { return "\uf049"; } }
        public static string Backward { get { return "\uf04a"; } }
        public static string Play { get { return "\uf04b"; } }
        public static string Pause { get { return "\uf04c"; } }
        public static string Stop { get { return "\uf04d"; } }
        public static string Forward { get { return "\uf04e"; } }
        public static string FastForward { get { return "\uf050"; } }
        public static string StepForward { get { return "\uf051"; } }
        public static string Eject { get { return "\uf052"; } }
        public static string ChevronLeft { get { return "\uf053"; } }
        public static string ChevronRight { get { return "\uf054"; } }
        public static string PlusCircle { get { return "\uf055"; } }
        public static string MinusCircle { get { return "\uf056"; } }
        public static string TimesCircle { get { return "\uf057"; } }
        public static string CheckCircle { get { return "\uf058"; } }
        public static string QuestionCircle { get { return "\uf059"; } }
        public static string InfoCircle { get { return "\uf05a"; } }
        public static string Crosshairs { get { return "\uf05b"; } }
        public static string Ban { get { return "\uf05e"; } }
        public static string ArrowLeft { get { return "\uf060"; } }
        public static string ArrowRight { get { return "\uf061"; } }
        public static string ArrowUp { get { return "\uf062"; } }
        public static string ArrowDown { get { return "\uf063"; } }
        public static string Share { get { return "\uf064"; } }
        public static string Expand { get { return "\uf065"; } }
        public static string Compress { get { return "\uf066"; } }
        public static string Plus { get { return "\uf067"; } }
        public static string Minus { get { return "\uf068"; } }
        public static string Asterisk { get { return "\uf069"; } }
        public static string ExclamationCircle { get { return "\uf06a"; } }
        public static string Gift { get { return "\uf06b"; } }
        public static string Leaf { get { return "\uf06c"; } }
        public static string Fire { get { return "\uf06d"; } }
        public static string Eye { get { return "\uf06e"; } }
        public static string EyeSlash { get { return "\uf070"; } }
        public static string ExclamationTriangle { get { return "\uf071"; } }
        public static string Plane { get { return "\uf072"; } }
        public static string CalendarAlt { get { return "\uf073"; } }
        public static string Random { get { return "\uf074"; } }
        public static string Comment { get { return "\uf075"; } }
        public static string Magnet { get { return "\uf076"; } }
        public static string ChevronUp { get { return "\uf077"; } }
        public static string ChevronDown { get { return "\uf078"; } }
        public static string Retweet { get { return "\uf079"; } }
        public static string ShoppingCart { get { return "\uf07a"; } }
        public static string Folder { get { return "\uf07b"; } }
        public static string FolderOpen { get { return "\uf07c"; } }
        public static string ChartBar { get { return "\uf080"; } }
        public static string CameraRetro { get { return "\uf083"; } }
        public static string Key { get { return "\uf084"; } }
        public static string Cogs { get { return "\uf085"; } }
        public static string Comments { get { return "\uf086"; } }
        public static string StarHalf { get { return "\uf089"; } }
        public static string Thumbtack { get { return "\uf08d"; } }
        public static string Trophy { get { return "\uf091"; } }
        public static string Upload { get { return "\uf093"; } }
        public static string Lemon { get { return "\uf094"; } }
        public static string Phone { get { return "\uf095"; } }
        public static string PhoneSquare { get { return "\uf098"; } }
        public static string Unlock { get { return "\uf09c"; } }
        public static string CreditCard { get { return "\uf09d"; } }
        public static string Rss { get { return "\uf09e"; } }
        public static string Hdd { get { return "\uf0a0"; } }
        public static string Bullhorn { get { return "\uf0a1"; } }
        public static string Certificate { get { return "\uf0a3"; } }
        public static string HandPointRight { get { return "\uf0a4"; } }
        public static string HandPointLeft { get { return "\uf0a5"; } }
        public static string HandPointUp { get { return "\uf0a6"; } }
        public static string HandPointDown { get { return "\uf0a7"; } }
        public static string ArrowCircleLeft { get { return "\uf0a8"; } }
        public static string ArrowCircleRight { get { return "\uf0a9"; } }
        public static string ArrowCircleUp { get { return "\uf0aa"; } }
        public static string ArrowCircleDown { get { return "\uf0ab"; } }
        public static string Globe { get { return "\uf0ac"; } }
        public static string Wrench { get { return "\uf0ad"; } }
        public static string Tasks { get { return "\uf0ae"; } }
        public static string Filter { get { return "\uf0b0"; } }
        public static string Briefcase { get { return "\uf0b1"; } }
        public static string ArrowsAlt { get { return "\uf0b2"; } }
        public static string Users { get { return "\uf0c0"; } }
        public static string Link { get { return "\uf0c1"; } }
        public static string Cloud { get { return "\uf0c2"; } }
        public static string Flask { get { return "\uf0c3"; } }
        public static string Cut { get { return "\uf0c4"; } }
        public static string Copy { get { return "\uf0c5"; } }
        public static string Paperclip { get { return "\uf0c6"; } }
        public static string Save { get { return "\uf0c7"; } }
        public static string Square { get { return "\uf0c8"; } }
        public static string Bars { get { return "\uf0c9"; } }
        public static string ListUl { get { return "\uf0ca"; } }
        public static string ListOl { get { return "\uf0cb"; } }
        public static string Strikethrough { get { return "\uf0cc"; } }
        public static string Underline { get { return "\uf0cd"; } }
        public static string Table { get { return "\uf0ce"; } }
        public static string Magic { get { return "\uf0d0"; } }
        public static string Truck { get { return "\uf0d1"; } }
        public static string MoneyBill { get { return "\uf0d6"; } }
        public static string CaretDown { get { return "\uf0d7"; } }
        public static string CaretUp { get { return "\uf0d8"; } }
        public static string CaretLeft { get { return "\uf0d9"; } }
        public static string CaretRight { get { return "\uf0da"; } }
        public static string Columns { get { return "\uf0db"; } }
        public static string Sort { get { return "\uf0dc"; } }
        public static string SortDown { get { return "\uf0dd"; } }
        public static string SortUp { get { return "\uf0de"; } }
        public static string Envelope { get { return "\uf0e0"; } }
        public static string Undo { get { return "\uf0e2"; } }
        public static string Gavel { get { return "\uf0e3"; } }
        public static string Bolt { get { return "\uf0e7"; } }
        public static string Sitemap { get { return "\uf0e8"; } }
        public static string Umbrella { get { return "\uf0e9"; } }
        public static string Paste { get { return "\uf0ea"; } }
        public static string Lightbulb { get { return "\uf0eb"; } }
        public static string UserMd { get { return "\uf0f0"; } }
        public static string Stethoscope { get { return "\uf0f1"; } }
        public static string Suitcase { get { return "\uf0f2"; } }
        public static string Bell { get { return "\uf0f3"; } }
        public static string Coffee { get { return "\uf0f4"; } }
        public static string Hospital { get { return "\uf0f8"; } }
        public static string Ambulance { get { return "\uf0f9"; } }
        public static string Medkit { get { return "\uf0fa"; } }
        public static string FighterJet { get { return "\uf0fb"; } }
        public static string Beer { get { return "\uf0fc"; } }
        public static string HSquare { get { return "\uf0fd"; } }
        public static string PlusSquare { get { return "\uf0fe"; } }
        public static string AngleDoubleLeft { get { return "\uf100"; } }
        public static string AngleDoubleRight { get { return "\uf101"; } }
        public static string AngleDoubleUp { get { return "\uf102"; } }
        public static string AngleDoubleDown { get { return "\uf103"; } }
        public static string AngleLeft { get { return "\uf104"; } }
        public static string AngleRight { get { return "\uf105"; } }
        public static string AngleUp { get { return "\uf106"; } }
        public static string AngleDown { get { return "\uf107"; } }
        public static string Desktop { get { return "\uf108"; } }
        public static string Laptop { get { return "\uf109"; } }
        public static string Tablet { get { return "\uf10a"; } }
        public static string Mobile { get { return "\uf10b"; } }
        public static string QuoteLeft { get { return "\uf10d"; } }
        public static string QuoteRight { get { return "\uf10e"; } }
        public static string Spinner { get { return "\uf110"; } }
        public static string Circle { get { return "\uf111"; } }
        public static string Smile { get { return "\uf118"; } }
        public static string Frown { get { return "\uf119"; } }
        public static string Meh { get { return "\uf11a"; } }
        public static string Gamepad { get { return "\uf11b"; } }
        public static string Keyboard { get { return "\uf11c"; } }
        public static string FlagCheckered { get { return "\uf11e"; } }
        public static string Terminal { get { return "\uf120"; } }
        public static string Code { get { return "\uf121"; } }
        public static string ReplyAll { get { return "\uf122"; } }
        public static string LocationArrow { get { return "\uf124"; } }
        public static string Crop { get { return "\uf125"; } }
        public static string CodeBranch { get { return "\uf126"; } }
        public static string Unlink { get { return "\uf127"; } }
        public static string Question { get { return "\uf128"; } }
        public static string Info { get { return "\uf129"; } }
        public static string Exclamation { get { return "\uf12a"; } }
        public static string Superscript { get { return "\uf12b"; } }
        public static string Subscript { get { return "\uf12c"; } }
        public static string Eraser { get { return "\uf12d"; } }
        public static string PuzzlePiece { get { return "\uf12e"; } }
        public static string Microphone { get { return "\uf130"; } }
        public static string MicrophoneSlash { get { return "\uf131"; } }
        public static string Calendar { get { return "\uf133"; } }
        public static string FireExtinguisher { get { return "\uf134"; } }
        public static string Rocket { get { return "\uf135"; } }
        public static string ChevronCircleLeft { get { return "\uf137"; } }
        public static string ChevronCircleRight { get { return "\uf138"; } }
        public static string ChevronCircleUp { get { return "\uf139"; } }
        public static string ChevronCircleDown { get { return "\uf13a"; } }
        public static string Anchor { get { return "\uf13d"; } }
        public static string UnlockAlt { get { return "\uf13e"; } }
        public static string Bullseye { get { return "\uf140"; } }
        public static string EllipsisH { get { return "\uf141"; } }
        public static string EllipsisV { get { return "\uf142"; } }
        public static string RssSquare { get { return "\uf143"; } }
        public static string PlayCircle { get { return "\uf144"; } }
        public static string MinusSquare { get { return "\uf146"; } }
        public static string CheckSquare { get { return "\uf14a"; } }
        public static string PenSquare { get { return "\uf14b"; } }
        public static string ShareSquare { get { return "\uf14d"; } }
        public static string Compass { get { return "\uf14e"; } }
        public static string CaretSquareDown { get { return "\uf150"; } }
        public static string CaretSquareUp { get { return "\uf151"; } }
        public static string CaretSquareRight { get { return "\uf152"; } }
        public static string EuroSign { get { return "\uf153"; } }
        public static string PoundSign { get { return "\uf154"; } }
        public static string DollarSign { get { return "\uf155"; } }
        public static string RupeeSign { get { return "\uf156"; } }
        public static string YenSign { get { return "\uf157"; } }
        public static string RubleSign { get { return "\uf158"; } }
        public static string WonSign { get { return "\uf159"; } }
        public static string File { get { return "\uf15b"; } }
        public static string FileAlt { get { return "\uf15c"; } }
        public static string SortAlphaDown { get { return "\uf15d"; } }
        public static string SortAlphaUp { get { return "\uf15e"; } }
        public static string SortAmountDown { get { return "\uf160"; } }
        public static string SortAmountUp { get { return "\uf161"; } }
        public static string SortNumericDown { get { return "\uf162"; } }
        public static string SortNumericUp { get { return "\uf163"; } }
        public static string ThumbsUp { get { return "\uf164"; } }
        public static string ThumbsDown { get { return "\uf165"; } }
        public static string Female { get { return "\uf182"; } }
        public static string Male { get { return "\uf183"; } }
        public static string Sun { get { return "\uf185"; } }
        public static string Moon { get { return "\uf186"; } }
        public static string Archive { get { return "\uf187"; } }
        public static string Bug { get { return "\uf188"; } }
        public static string CaretSquareLeft { get { return "\uf191"; } }
        public static string DotCircle { get { return "\uf192"; } }
        public static string Wheelchair { get { return "\uf193"; } }
        public static string LiraSign { get { return "\uf195"; } }
        public static string SpaceShuttle { get { return "\uf197"; } }
        public static string EnvelopeSquare { get { return "\uf199"; } }
        public static string University { get { return "\uf19c"; } }
        public static string GraduationCap { get { return "\uf19d"; } }
        public static string Language { get { return "\uf1ab"; } }
        public static string Fax { get { return "\uf1ac"; } }
        public static string Building { get { return "\uf1ad"; } }
        public static string Child { get { return "\uf1ae"; } }
        public static string Paw { get { return "\uf1b0"; } }
        public static string Cube { get { return "\uf1b2"; } }
        public static string Cubes { get { return "\uf1b3"; } }
        public static string Recycle { get { return "\uf1b8"; } }
        public static string Car { get { return "\uf1b9"; } }
        public static string Taxi { get { return "\uf1ba"; } }
        public static string Tree { get { return "\uf1bb"; } }
        public static string Database { get { return "\uf1c0"; } }
        public static string FilePdf { get { return "\uf1c1"; } }
        public static string FileWord { get { return "\uf1c2"; } }
        public static string FileExcel { get { return "\uf1c3"; } }
        public static string FilePowerpoint { get { return "\uf1c4"; } }
        public static string FileImage { get { return "\uf1c5"; } }
        public static string FileArchive { get { return "\uf1c6"; } }
        public static string FileAudio { get { return "\uf1c7"; } }
        public static string FileVideo { get { return "\uf1c8"; } }
        public static string FileCode { get { return "\uf1c9"; } }
        public static string LifeRing { get { return "\uf1cd"; } }
        public static string CircleNotch { get { return "\uf1ce"; } }
        public static string PaperPlane { get { return "\uf1d8"; } }
        public static string History { get { return "\uf1da"; } }
        public static string Heading { get { return "\uf1dc"; } }
        public static string Paragraph { get { return "\uf1dd"; } }
        public static string SlidersH { get { return "\uf1de"; } }
        public static string ShareAlt { get { return "\uf1e0"; } }
        public static string ShareAltSquare { get { return "\uf1e1"; } }
        public static string Bomb { get { return "\uf1e2"; } }
        public static string Futbol { get { return "\uf1e3"; } }
        public static string Tty { get { return "\uf1e4"; } }
        public static string Binoculars { get { return "\uf1e5"; } }
        public static string Plug { get { return "\uf1e6"; } }
        public static string Newspaper { get { return "\uf1ea"; } }
        public static string Wifi { get { return "\uf1eb"; } }
        public static string Calculator { get { return "\uf1ec"; } }
        public static string BellSlash { get { return "\uf1f6"; } }
        public static string Trash { get { return "\uf1f8"; } }
        public static string Copyright { get { return "\uf1f9"; } }
        public static string At { get { return "\uf1fa"; } }
        public static string EyeDropper { get { return "\uf1fb"; } }
        public static string PaintBrush { get { return "\uf1fc"; } }
        public static string BirthdayCake { get { return "\uf1fd"; } }
        public static string ChartArea { get { return "\uf1fe"; } }
        public static string ChartPie { get { return "\uf200"; } }
        public static string ChartLine { get { return "\uf201"; } }
        public static string ToggleOff { get { return "\uf204"; } }
        public static string ToggleOn { get { return "\uf205"; } }
        public static string Bicycle { get { return "\uf206"; } }
        public static string Bus { get { return "\uf207"; } }
        public static string ClosedCaptioning { get { return "\uf20a"; } }
        public static string ShekelSign { get { return "\uf20b"; } }
        public static string CartPlus { get { return "\uf217"; } }
        public static string CartArrowDown { get { return "\uf218"; } }
        public static string Ship { get { return "\uf21a"; } }
        public static string UserSecret { get { return "\uf21b"; } }
        public static string Motorcycle { get { return "\uf21c"; } }
        public static string StreetView { get { return "\uf21d"; } }
        public static string Heartbeat { get { return "\uf21e"; } }
        public static string Venus { get { return "\uf221"; } }
        public static string Mars { get { return "\uf222"; } }
        public static string Mercury { get { return "\uf223"; } }
        public static string Transgender { get { return "\uf224"; } }
        public static string TransgenderAlt { get { return "\uf225"; } }
        public static string VenusDouble { get { return "\uf226"; } }
        public static string MarsDouble { get { return "\uf227"; } }
        public static string VenusMars { get { return "\uf228"; } }
        public static string MarsStroke { get { return "\uf229"; } }
        public static string MarsStrokeV { get { return "\uf22a"; } }
        public static string MarsStrokeH { get { return "\uf22b"; } }
        public static string Neuter { get { return "\uf22c"; } }
        public static string Genderless { get { return "\uf22d"; } }
        public static string Server { get { return "\uf233"; } }
        public static string UserPlus { get { return "\uf234"; } }
        public static string UserTimes { get { return "\uf235"; } }
        public static string Bed { get { return "\uf236"; } }
        public static string Train { get { return "\uf238"; } }
        public static string Subway { get { return "\uf239"; } }
        public static string BatteryFull { get { return "\uf240"; } }
        public static string BatteryThreeQuarters { get { return "\uf241"; } }
        public static string BatteryHalf { get { return "\uf242"; } }
        public static string BatteryQuarter { get { return "\uf243"; } }
        public static string BatteryEmpty { get { return "\uf244"; } }
        public static string MousePointer { get { return "\uf245"; } }
        public static string ICursor { get { return "\uf246"; } }
        public static string ObjectGroup { get { return "\uf247"; } }
        public static string ObjectUngroup { get { return "\uf248"; } }
        public static string StickyNote { get { return "\uf249"; } }
        public static string Clone { get { return "\uf24d"; } }
        public static string BalanceScale { get { return "\uf24e"; } }
        public static string HourglassStart { get { return "\uf251"; } }
        public static string HourglassHalf { get { return "\uf252"; } }
        public static string HourglassEnd { get { return "\uf253"; } }
        public static string Hourglass { get { return "\uf254"; } }
        public static string HandRock { get { return "\uf255"; } }
        public static string HandPaper { get { return "\uf256"; } }
        public static string HandScissors { get { return "\uf257"; } }
        public static string HandLizard { get { return "\uf258"; } }
        public static string HandSpock { get { return "\uf259"; } }
        public static string HandPointer { get { return "\uf25a"; } }
        public static string HandPeace { get { return "\uf25b"; } }
        public static string Trademark { get { return "\uf25c"; } }
        public static string Registered { get { return "\uf25d"; } }
        public static string Tv { get { return "\uf26c"; } }
        public static string CalendarPlus { get { return "\uf271"; } }
        public static string CalendarMinus { get { return "\uf272"; } }
        public static string CalendarTimes { get { return "\uf273"; } }
        public static string CalendarCheck { get { return "\uf274"; } }
        public static string Industry { get { return "\uf275"; } }
        public static string MapPin { get { return "\uf276"; } }
        public static string MapSigns { get { return "\uf277"; } }
        public static string Map { get { return "\uf279"; } }
        public static string CommentAlt { get { return "\uf27a"; } }
        public static string PauseCircle { get { return "\uf28b"; } }
        public static string StopCircle { get { return "\uf28d"; } }
        public static string ShoppingBag { get { return "\uf290"; } }
        public static string ShoppingBasket { get { return "\uf291"; } }
        public static string Hashtag { get { return "\uf292"; } }
        public static string Percent { get { return "\uf295"; } }
        public static string UniversalAccess { get { return "\uf29a"; } }
        public static string Blind { get { return "\uf29d"; } }
        public static string AudioDescription { get { return "\uf29e"; } }
        public static string PhoneVolume { get { return "\uf2a0"; } }
        public static string Braille { get { return "\uf2a1"; } }
        public static string AssistiveListeningSystems { get { return "\uf2a2"; } }
        public static string AmericanSignLanguageInterpreting { get { return "\uf2a3"; } }
        public static string Deaf { get { return "\uf2a4"; } }
        public static string SignLanguage { get { return "\uf2a7"; } }
        public static string LowVision { get { return "\uf2a8"; } }
        public static string Handshake { get { return "\uf2b5"; } }
        public static string EnvelopeOpen { get { return "\uf2b6"; } }
        public static string AddressBook { get { return "\uf2b9"; } }
        public static string AddressCard { get { return "\uf2bb"; } }
        public static string UserCircle { get { return "\uf2bd"; } }
        public static string IdBadge { get { return "\uf2c1"; } }
        public static string IdCard { get { return "\uf2c2"; } }
        public static string ThermometerFull { get { return "\uf2c7"; } }
        public static string ThermometerThreeQuarters { get { return "\uf2c8"; } }
        public static string ThermometerHalf { get { return "\uf2c9"; } }
        public static string ThermometerQuarter { get { return "\uf2ca"; } }
        public static string ThermometerEmpty { get { return "\uf2cb"; } }
        public static string Shower { get { return "\uf2cc"; } }
        public static string Bath { get { return "\uf2cd"; } }
        public static string Podcast { get { return "\uf2ce"; } }
        public static string WindowMaximize { get { return "\uf2d0"; } }
        public static string WindowMinimize { get { return "\uf2d1"; } }
        public static string WindowRestore { get { return "\uf2d2"; } }
        public static string Microchip { get { return "\uf2db"; } }
        public static string Snowflake { get { return "\uf2dc"; } }
        public static string UtensilSpoon { get { return "\uf2e5"; } }
        public static string Utensils { get { return "\uf2e7"; } }
        public static string UndoAlt { get { return "\uf2ea"; } }
        public static string TrashAlt { get { return "\uf2ed"; } }
        public static string SyncAlt { get { return "\uf2f1"; } }
        public static string Stopwatch { get { return "\uf2f2"; } }
        public static string SignOutAlt { get { return "\uf2f5"; } }
        public static string SignInAlt { get { return "\uf2f6"; } }
        public static string RedoAlt { get { return "\uf2f9"; } }
        public static string Poo { get { return "\uf2fe"; } }
        public static string Images { get { return "\uf302"; } }
        public static string PencilAlt { get { return "\uf303"; } }
        public static string Pen { get { return "\uf304"; } }
        public static string PenAlt { get { return "\uf305"; } }
        public static string LongArrowAltDown { get { return "\uf309"; } }
        public static string LongArrowAltLeft { get { return "\uf30a"; } }
        public static string LongArrowAltRight { get { return "\uf30b"; } }
        public static string LongArrowAltUp { get { return "\uf30c"; } }
        public static string ExpandArrowsAlt { get { return "\uf31e"; } }
        public static string Clipboard { get { return "\uf328"; } }
        public static string ArrowsAltH { get { return "\uf337"; } }
        public static string ArrowsAltV { get { return "\uf338"; } }
        public static string ArrowAltCircleDown { get { return "\uf358"; } }
        public static string ArrowAltCircleLeft { get { return "\uf359"; } }
        public static string ArrowAltCircleRight { get { return "\uf35a"; } }
        public static string ArrowAltCircleUp { get { return "\uf35b"; } }
        public static string ExternalLinkAlt { get { return "\uf35d"; } }
        public static string ExternalLinkSquareAlt { get { return "\uf360"; } }
        public static string ExchangeAlt { get { return "\uf362"; } }
        public static string CloudDownloadAlt { get { return "\uf381"; } }
        public static string CloudUploadAlt { get { return "\uf382"; } }
        public static string Gem { get { return "\uf3a5"; } }
        public static string LevelDownAlt { get { return "\uf3be"; } }
        public static string LevelUpAlt { get { return "\uf3bf"; } }
        public static string LockOpen { get { return "\uf3c1"; } }
        public static string MapMarkerAlt { get { return "\uf3c5"; } }
        public static string MicrophoneAlt { get { return "\uf3c9"; } }
        public static string MobileAlt { get { return "\uf3cd"; } }
        public static string MoneyBillAlt { get { return "\uf3d1"; } }
        public static string PhoneSlash { get { return "\uf3dd"; } }
        public static string Portrait { get { return "\uf3e0"; } }
        public static string Reply { get { return "\uf3e5"; } }
        public static string ShieldAlt { get { return "\uf3ed"; } }
        public static string TabletAlt { get { return "\uf3fa"; } }
        public static string TachometerAlt { get { return "\uf3fd"; } }
        public static string TicketAlt { get { return "\uf3ff"; } }
        public static string UserAlt { get { return "\uf406"; } }
        public static string WindowClose { get { return "\uf410"; } }
        public static string BaseballBall { get { return "\uf433"; } }
        public static string BasketballBall { get { return "\uf434"; } }
        public static string BowlingBall { get { return "\uf436"; } }
        public static string Chess { get { return "\uf439"; } }
        public static string ChessBishop { get { return "\uf43a"; } }
        public static string ChessBoard { get { return "\uf43c"; } }
        public static string ChessKing { get { return "\uf43f"; } }
        public static string ChessKnight { get { return "\uf441"; } }
        public static string ChessPawn { get { return "\uf443"; } }
        public static string ChessQueen { get { return "\uf445"; } }
        public static string ChessRook { get { return "\uf447"; } }
        public static string Dumbbell { get { return "\uf44b"; } }
        public static string FootballBall { get { return "\uf44e"; } }
        public static string GolfBall { get { return "\uf450"; } }
        public static string HockeyPuck { get { return "\uf453"; } }
        public static string Quidditch { get { return "\uf458"; } }
        public static string SquareFull { get { return "\uf45c"; } }
        public static string TableTennis { get { return "\uf45d"; } }
        public static string VolleyballBall { get { return "\uf45f"; } }
        public static string Allergies { get { return "\uf461"; } }
        public static string BandAid { get { return "\uf462"; } }
        public static string Box { get { return "\uf466"; } }
        public static string Boxes { get { return "\uf468"; } }
        public static string BriefcaseMedical { get { return "\uf469"; } }
        public static string Burn { get { return "\uf46a"; } }
        public static string Capsules { get { return "\uf46b"; } }
        public static string ClipboardCheck { get { return "\uf46c"; } }
        public static string ClipboardList { get { return "\uf46d"; } }
        public static string Diagnoses { get { return "\uf470"; } }
        public static string Dna { get { return "\uf471"; } }
        public static string Dolly { get { return "\uf472"; } }
        public static string DollyFlatbed { get { return "\uf474"; } }
        public static string FileMedical { get { return "\uf477"; } }
        public static string FileMedicalAlt { get { return "\uf478"; } }
        public static string FirstAid { get { return "\uf479"; } }
        public static string HospitalAlt { get { return "\uf47d"; } }
        public static string HospitalSymbol { get { return "\uf47e"; } }
        public static string IdCardAlt { get { return "\uf47f"; } }
        public static string NotesMedical { get { return "\uf481"; } }
        public static string Pallet { get { return "\uf482"; } }
        public static string Pills { get { return "\uf484"; } }
        public static string PrescriptionBottle { get { return "\uf485"; } }
        public static string PrescriptionBottleAlt { get { return "\uf486"; } }
        public static string Procedures { get { return "\uf487"; } }
        public static string ShippingFast { get { return "\uf48b"; } }
        public static string Smoking { get { return "\uf48d"; } }
        public static string Syringe { get { return "\uf48e"; } }
        public static string Tablets { get { return "\uf490"; } }
        public static string Thermometer { get { return "\uf491"; } }
        public static string Vial { get { return "\uf492"; } }
        public static string Vials { get { return "\uf493"; } }
        public static string Warehouse { get { return "\uf494"; } }
        public static string Weight { get { return "\uf496"; } }
        public static string XRay { get { return "\uf497"; } }
        public static string BoxOpen { get { return "\uf49e"; } }
        public static string CommentDots { get { return "\uf4ad"; } }
        public static string CommentSlash { get { return "\uf4b3"; } }
        public static string Couch { get { return "\uf4b8"; } }
        public static string Donate { get { return "\uf4b9"; } }
        public static string Dove { get { return "\uf4ba"; } }
        public static string HandHolding { get { return "\uf4bd"; } }
        public static string HandHoldingHeart { get { return "\uf4be"; } }
        public static string HandHoldingUsd { get { return "\uf4c0"; } }
        public static string Hands { get { return "\uf4c2"; } }
        public static string HandsHelping { get { return "\uf4c4"; } }
        public static string ParachuteBox { get { return "\uf4cd"; } }
        public static string PeopleCarry { get { return "\uf4ce"; } }
        public static string PiggyBank { get { return "\uf4d3"; } }
        public static string Ribbon { get { return "\uf4d6"; } }
        public static string Route { get { return "\uf4d7"; } }
        public static string Seedling { get { return "\uf4d8"; } }
        public static string Sign { get { return "\uf4d9"; } }
        public static string SmileWink { get { return "\uf4da"; } }
        public static string Tape { get { return "\uf4db"; } }
        public static string TruckLoading { get { return "\uf4de"; } }
        public static string TruckMoving { get { return "\uf4df"; } }
        public static string VideoSlash { get { return "\uf4e2"; } }
        public static string WineGlass { get { return "\uf4e3"; } }
        public static string UserAltSlash { get { return "\uf4fa"; } }
        public static string UserAstronaut { get { return "\uf4fb"; } }
        public static string UserCheck { get { return "\uf4fc"; } }
        public static string UserClock { get { return "\uf4fd"; } }
        public static string UserCog { get { return "\uf4fe"; } }
        public static string UserEdit { get { return "\uf4ff"; } }
        public static string UserFriends { get { return "\uf500"; } }
        public static string UserGraduate { get { return "\uf501"; } }
        public static string UserLock { get { return "\uf502"; } }
        public static string UserMinus { get { return "\uf503"; } }
        public static string UserNinja { get { return "\uf504"; } }
        public static string UserShield { get { return "\uf505"; } }
        public static string UserSlash { get { return "\uf506"; } }
        public static string UserTag { get { return "\uf507"; } }
        public static string UserTie { get { return "\uf508"; } }
        public static string UsersCog { get { return "\uf509"; } }
        public static string Blender { get { return "\uf517"; } }
        public static string BookOpen { get { return "\uf518"; } }
        public static string BroadcastTower { get { return "\uf519"; } }
        public static string Broom { get { return "\uf51a"; } }
        public static string Chalkboard { get { return "\uf51b"; } }
        public static string ChalkboardTeacher { get { return "\uf51c"; } }
        public static string Church { get { return "\uf51d"; } }
        public static string Coins { get { return "\uf51e"; } }
        public static string CompactDisc { get { return "\uf51f"; } }
        public static string Crow { get { return "\uf520"; } }
        public static string Crown { get { return "\uf521"; } }
        public static string Dice { get { return "\uf522"; } }
        public static string DiceFive { get { return "\uf523"; } }
        public static string DiceFour { get { return "\uf524"; } }
        public static string DiceOne { get { return "\uf525"; } }
        public static string DiceSix { get { return "\uf526"; } }
        public static string DiceThree { get { return "\uf527"; } }
        public static string DiceTwo { get { return "\uf528"; } }
        public static string Divide { get { return "\uf529"; } }
        public static string DoorClosed { get { return "\uf52a"; } }
        public static string DoorOpen { get { return "\uf52b"; } }
        public static string Equals { get { return "\uf52c"; } }
        public static string Feather { get { return "\uf52d"; } }
        public static string Frog { get { return "\uf52e"; } }
        public static string GasPump { get { return "\uf52f"; } }
        public static string Glasses { get { return "\uf530"; } }
        public static string GreaterThan { get { return "\uf531"; } }
        public static string GreaterThanEqual { get { return "\uf532"; } }
        public static string Helicopter { get { return "\uf533"; } }
        public static string Infinity { get { return "\uf534"; } }
        public static string KiwiBird { get { return "\uf535"; } }
        public static string LessThan { get { return "\uf536"; } }
        public static string LessThanEqual { get { return "\uf537"; } }
        public static string Memory { get { return "\uf538"; } }
        public static string MicrophoneAltSlash { get { return "\uf539"; } }
        public static string MoneyBillWave { get { return "\uf53a"; } }
        public static string MoneyBillWaveAlt { get { return "\uf53b"; } }
        public static string MoneyCheck { get { return "\uf53c"; } }
        public static string MoneyCheckAlt { get { return "\uf53d"; } }
        public static string NotEqual { get { return "\uf53e"; } }
        public static string Palette { get { return "\uf53f"; } }
        public static string Parking { get { return "\uf540"; } }
        public static string Percentage { get { return "\uf541"; } }
        public static string ProjectDiagram { get { return "\uf542"; } }
        public static string Receipt { get { return "\uf543"; } }
        public static string Robot { get { return "\uf544"; } }
        public static string Ruler { get { return "\uf545"; } }
        public static string RulerCombined { get { return "\uf546"; } }
        public static string RulerHorizontal { get { return "\uf547"; } }
        public static string RulerVertical { get { return "\uf548"; } }
        public static string School { get { return "\uf549"; } }
        public static string Screwdriver { get { return "\uf54a"; } }
        public static string ShoePrints { get { return "\uf54b"; } }
        public static string Skull { get { return "\uf54c"; } }
        public static string SmokingBan { get { return "\uf54d"; } }
        public static string Store { get { return "\uf54e"; } }
        public static string StoreAlt { get { return "\uf54f"; } }
        public static string Stream { get { return "\uf550"; } }
        public static string Stroopwafel { get { return "\uf551"; } }
        public static string Toolbox { get { return "\uf552"; } }
        public static string Tshirt { get { return "\uf553"; } }
        public static string Walking { get { return "\uf554"; } }
        public static string Wallet { get { return "\uf555"; } }
        public static string Angry { get { return "\uf556"; } }
        public static string Archway { get { return "\uf557"; } }
        public static string Atlas { get { return "\uf558"; } }
        public static string Award { get { return "\uf559"; } }
        public static string Backspace { get { return "\uf55a"; } }
        public static string BezierCurve { get { return "\uf55b"; } }
        public static string Bong { get { return "\uf55c"; } }
        public static string Brush { get { return "\uf55d"; } }
        public static string BusAlt { get { return "\uf55e"; } }
        public static string Cannabis { get { return "\uf55f"; } }
        public static string CheckDouble { get { return "\uf560"; } }
        public static string Cocktail { get { return "\uf561"; } }
        public static string ConciergeBell { get { return "\uf562"; } }
        public static string Cookie { get { return "\uf563"; } }
        public static string CookieBite { get { return "\uf564"; } }
        public static string CropAlt { get { return "\uf565"; } }
        public static string DigitalTachograph { get { return "\uf566"; } }
        public static string Dizzy { get { return "\uf567"; } }
        public static string DraftingCompass { get { return "\uf568"; } }
        public static string Drum { get { return "\uf569"; } }
        public static string DrumSteelpan { get { return "\uf56a"; } }
        public static string FeatherAlt { get { return "\uf56b"; } }
        public static string FileContract { get { return "\uf56c"; } }
        public static string FileDownload { get { return "\uf56d"; } }
        public static string FileExport { get { return "\uf56e"; } }
        public static string FileImport { get { return "\uf56f"; } }
        public static string FileInvoice { get { return "\uf570"; } }
        public static string FileInvoiceDollar { get { return "\uf571"; } }
        public static string FilePrescription { get { return "\uf572"; } }
        public static string FileSignature { get { return "\uf573"; } }
        public static string FileUpload { get { return "\uf574"; } }
        public static string Fill { get { return "\uf575"; } }
        public static string FillDrip { get { return "\uf576"; } }
        public static string Fingerprint { get { return "\uf577"; } }
        public static string Fish { get { return "\uf578"; } }
        public static string Flushed { get { return "\uf579"; } }
        public static string FrownOpen { get { return "\uf57a"; } }
        public static string GlassMartiniAlt { get { return "\uf57b"; } }
        public static string GlobeAfrica { get { return "\uf57c"; } }
        public static string GlobeAmericas { get { return "\uf57d"; } }
        public static string GlobeAsia { get { return "\uf57e"; } }
        public static string Grimace { get { return "\uf57f"; } }
        public static string Grin { get { return "\uf580"; } }
        public static string GrinAlt { get { return "\uf581"; } }
        public static string GrinBeam { get { return "\uf582"; } }
        public static string GrinBeamSweat { get { return "\uf583"; } }
        public static string GrinHearts { get { return "\uf584"; } }
        public static string GrinSquint { get { return "\uf585"; } }
        public static string GrinSquintTears { get { return "\uf586"; } }
        public static string GrinStars { get { return "\uf587"; } }
        public static string GrinTears { get { return "\uf588"; } }
        public static string GrinTongue { get { return "\uf589"; } }
        public static string GrinTongueSquint { get { return "\uf58a"; } }
        public static string GrinTongueWink { get { return "\uf58b"; } }
        public static string GrinWink { get { return "\uf58c"; } }
        public static string GripHorizontal { get { return "\uf58d"; } }
        public static string GripVertical { get { return "\uf58e"; } }
        public static string HeadphonesAlt { get { return "\uf58f"; } }
        public static string Headset { get { return "\uf590"; } }
        public static string Highlighter { get { return "\uf591"; } }
        public static string HotTub { get { return "\uf593"; } }
        public static string Hotel { get { return "\uf594"; } }
        public static string Joint { get { return "\uf595"; } }
        public static string Kiss { get { return "\uf596"; } }
        public static string KissBeam { get { return "\uf597"; } }
        public static string KissWinkHeart { get { return "\uf598"; } }
        public static string Laugh { get { return "\uf599"; } }
        public static string LaughBeam { get { return "\uf59a"; } }
        public static string LaughSquint { get { return "\uf59b"; } }
        public static string LaughWink { get { return "\uf59c"; } }
        public static string LuggageCart { get { return "\uf59d"; } }
        public static string MapMarked { get { return "\uf59f"; } }
        public static string MapMarkedAlt { get { return "\uf5a0"; } }
        public static string Marker { get { return "\uf5a1"; } }
        public static string Medal { get { return "\uf5a2"; } }
        public static string MehBlank { get { return "\uf5a4"; } }
        public static string MehRollingEyes { get { return "\uf5a5"; } }
        public static string Monument { get { return "\uf5a6"; } }
        public static string MortarPestle { get { return "\uf5a7"; } }
        public static string PaintRoller { get { return "\uf5aa"; } }
        public static string Passport { get { return "\uf5ab"; } }
        public static string PenFancy { get { return "\uf5ac"; } }
        public static string PenNib { get { return "\uf5ad"; } }
        public static string PencilRuler { get { return "\uf5ae"; } }
        public static string PlaneArrival { get { return "\uf5af"; } }
        public static string PlaneDeparture { get { return "\uf5b0"; } }
        public static string Prescription { get { return "\uf5b1"; } }
        public static string SadCry { get { return "\uf5b3"; } }
        public static string SadTear { get { return "\uf5b4"; } }
        public static string ShuttleVan { get { return "\uf5b6"; } }
        public static string Signature { get { return "\uf5b7"; } }
        public static string SmileBeam { get { return "\uf5b8"; } }
        public static string SolarPanel { get { return "\uf5ba"; } }
        public static string Spa { get { return "\uf5bb"; } }
        public static string Splotch { get { return "\uf5bc"; } }
        public static string SprayCan { get { return "\uf5bd"; } }
        public static string Stamp { get { return "\uf5bf"; } }
        public static string StarHalfAlt { get { return "\uf5c0"; } }
        public static string SuitcaseRolling { get { return "\uf5c1"; } }
        public static string Surprise { get { return "\uf5c2"; } }
        public static string Swatchbook { get { return "\uf5c3"; } }
        public static string Swimmer { get { return "\uf5c4"; } }
        public static string SwimmingPool { get { return "\uf5c5"; } }
        public static string TintSlash { get { return "\uf5c7"; } }
        public static string Tired { get { return "\uf5c8"; } }
        public static string Tooth { get { return "\uf5c9"; } }
        public static string UmbrellaBeach { get { return "\uf5ca"; } }
        public static string VectorSquare { get { return "\uf5cb"; } }
        public static string WeightHanging { get { return "\uf5cd"; } }
        public static string WineGlassAlt { get { return "\uf5ce"; } }
        public static string AirFreshener { get { return "\uf5d0"; } }
        public static string AppleAlt { get { return "\uf5d1"; } }
        public static string Atom { get { return "\uf5d2"; } }
        public static string Bone { get { return "\uf5d7"; } }
        public static string BookReader { get { return "\uf5da"; } }
        public static string Brain { get { return "\uf5dc"; } }
        public static string CarAlt { get { return "\uf5de"; } }
        public static string CarBattery { get { return "\uf5df"; } }
        public static string CarCrash { get { return "\uf5e1"; } }
        public static string CarSide { get { return "\uf5e4"; } }
        public static string ChargingStation { get { return "\uf5e7"; } }
        public static string Directions { get { return "\uf5eb"; } }
        public static string DrawPolygon { get { return "\uf5ee"; } }
        public static string LaptopCode { get { return "\uf5fc"; } }
        public static string LayerGroup { get { return "\uf5fd"; } }
        public static string Microscope { get { return "\uf610"; } }
        public static string OilCan { get { return "\uf613"; } }
        public static string Poop { get { return "\uf619"; } }
        public static string Shapes { get { return "\uf61f"; } }
        public static string StarOfLife { get { return "\uf621"; } }
        public static string Teeth { get { return "\uf62e"; } }
        public static string TeethOpen { get { return "\uf62f"; } }
        public static string TheaterMasks { get { return "\uf630"; } }
        public static string TrafficLight { get { return "\uf637"; } }
        public static string TruckMonster { get { return "\uf63b"; } }
        public static string TruckPickup { get { return "\uf63c"; } }
        public static string Ad { get { return "\uf641"; } }
        public static string Ankh { get { return "\uf644"; } }
        public static string Bible { get { return "\uf647"; } }
        public static string BusinessTime { get { return "\uf64a"; } }
        public static string City { get { return "\uf64f"; } }
        public static string CommentDollar { get { return "\uf651"; } }
        public static string CommentsDollar { get { return "\uf653"; } }
        public static string Cross { get { return "\uf654"; } }
        public static string Dharmachakra { get { return "\uf655"; } }
        public static string EnvelopeOpenText { get { return "\uf658"; } }
        public static string FolderMinus { get { return "\uf65d"; } }
        public static string FolderPlus { get { return "\uf65e"; } }
        public static string FunnelDollar { get { return "\uf662"; } }
        public static string Gopuram { get { return "\uf664"; } }
        public static string Hamsa { get { return "\uf665"; } }
        public static string Haykal { get { return "\uf666"; } }
        public static string Jedi { get { return "\uf669"; } }
        public static string JournalWhills { get { return "\uf66a"; } }
        public static string Kaaba { get { return "\uf66b"; } }
        public static string Khanda { get { return "\uf66d"; } }
        public static string Landmark { get { return "\uf66f"; } }
        public static string MailBulk { get { return "\uf674"; } }
        public static string Menorah { get { return "\uf676"; } }
        public static string Mosque { get { return "\uf678"; } }
        public static string Om { get { return "\uf679"; } }
        public static string Pastafarianism { get { return "\uf67b"; } }
        public static string Peace { get { return "\uf67c"; } }
        public static string PlaceOfWorship { get { return "\uf67f"; } }
        public static string Poll { get { return "\uf681"; } }
        public static string PollH { get { return "\uf682"; } }
        public static string Pray { get { return "\uf683"; } }
        public static string PrayingHands { get { return "\uf684"; } }
        public static string Quran { get { return "\uf687"; } }
        public static string SearchDollar { get { return "\uf688"; } }
        public static string SearchLocation { get { return "\uf689"; } }
        public static string Socks { get { return "\uf696"; } }
        public static string SquareRootAlt { get { return "\uf698"; } }
        public static string StarAndCrescent { get { return "\uf699"; } }
        public static string StarOfDavid { get { return "\uf69a"; } }
        public static string Synagogue { get { return "\uf69b"; } }
        public static string Torah { get { return "\uf6a0"; } }
        public static string ToriiGate { get { return "\uf6a1"; } }
        public static string Vihara { get { return "\uf6a7"; } }
        public static string VolumeMute { get { return "\uf6a9"; } }
        public static string YinYang { get { return "\uf6ad"; } }
        public static string BlenderPhone { get { return "\uf6b6"; } }
        public static string BookDead { get { return "\uf6b7"; } }
        public static string Campground { get { return "\uf6bb"; } }
        public static string Cat { get { return "\uf6be"; } }
        public static string Chair { get { return "\uf6c0"; } }
        public static string CloudMoon { get { return "\uf6c3"; } }
        public static string CloudSun { get { return "\uf6c4"; } }
        public static string DiceD20 { get { return "\uf6cf"; } }
        public static string DiceD6 { get { return "\uf6d1"; } }
        public static string Dog { get { return "\uf6d3"; } }
        public static string Dragon { get { return "\uf6d5"; } }
        public static string DrumstickBite { get { return "\uf6d7"; } }
        public static string Dungeon { get { return "\uf6d9"; } }
        public static string FileCsv { get { return "\uf6dd"; } }
        public static string FistRaised { get { return "\uf6de"; } }
        public static string Ghost { get { return "\uf6e2"; } }
        public static string Hammer { get { return "\uf6e3"; } }
        public static string Hanukiah { get { return "\uf6e6"; } }
        public static string HatWizard { get { return "\uf6e8"; } }
        public static string Hiking { get { return "\uf6ec"; } }
        public static string Hippo { get { return "\uf6ed"; } }
        public static string Horse { get { return "\uf6f0"; } }
        public static string HouseDamage { get { return "\uf6f1"; } }
        public static string Hryvnia { get { return "\uf6f2"; } }
        public static string Mask { get { return "\uf6fa"; } }
        public static string Mountain { get { return "\uf6fc"; } }
        public static string NetworkWired { get { return "\uf6ff"; } }
        public static string Otter { get { return "\uf700"; } }
        public static string Ring { get { return "\uf70b"; } }
        public static string Running { get { return "\uf70c"; } }
        public static string Scroll { get { return "\uf70e"; } }
        public static string SkullCrossbones { get { return "\uf714"; } }
        public static string Slash { get { return "\uf715"; } }
        public static string Spider { get { return "\uf717"; } }
        public static string ToiletPaper { get { return "\uf71e"; } }
        public static string Tractor { get { return "\uf722"; } }
        public static string UserInjured { get { return "\uf728"; } }
        public static string VrCardboard { get { return "\uf729"; } }
        public static string Wind { get { return "\uf72e"; } }
        public static string WineBottle { get { return "\uf72f"; } }
        public static string CloudMeatball { get { return "\uf73b"; } }
        public static string CloudMoonRain { get { return "\uf73c"; } }
        public static string CloudRain { get { return "\uf73d"; } }
        public static string CloudShowersHeavy { get { return "\uf740"; } }
        public static string CloudSunRain { get { return "\uf743"; } }
        public static string Democrat { get { return "\uf747"; } }
        public static string FlagUsa { get { return "\uf74d"; } }
        public static string Meteor { get { return "\uf753"; } }
        public static string PersonBooth { get { return "\uf756"; } }
        public static string PooStorm { get { return "\uf75a"; } }
        public static string Rainbow { get { return "\uf75b"; } }
        public static string Republican { get { return "\uf75e"; } }
        public static string Smog { get { return "\uf75f"; } }
        public static string TemperatureHigh { get { return "\uf769"; } }
        public static string TemperatureLow { get { return "\uf76b"; } }
        public static string VoteYea { get { return "\uf772"; } }
        public static string Water { get { return "\uf773"; } }
        public static string Baby { get { return "\uf77c"; } }
        public static string BabyCarriage { get { return "\uf77d"; } }
        public static string Biohazard { get { return "\uf780"; } }
        public static string Blog { get { return "\uf781"; } }
        public static string CalendarDay { get { return "\uf783"; } }
        public static string CalendarWeek { get { return "\uf784"; } }
        public static string CandyCane { get { return "\uf786"; } }
        public static string Carrot { get { return "\uf787"; } }
        public static string CashRegister { get { return "\uf788"; } }
        public static string CompressArrowsAlt { get { return "\uf78c"; } }
        public static string Dumpster { get { return "\uf793"; } }
        public static string DumpsterFire { get { return "\uf794"; } }
        public static string Ethernet { get { return "\uf796"; } }
        public static string Gifts { get { return "\uf79c"; } }
        public static string GlassCheers { get { return "\uf79f"; } }
        public static string GlassWhiskey { get { return "\uf7a0"; } }
        public static string GlobeEurope { get { return "\uf7a2"; } }
        public static string GripLines { get { return "\uf7a4"; } }
        public static string GripLinesVertical { get { return "\uf7a5"; } }
        public static string Guitar { get { return "\uf7a6"; } }
        public static string HeartBroken { get { return "\uf7a9"; } }
        public static string HollyBerry { get { return "\uf7aa"; } }
        public static string HorseHead { get { return "\uf7ab"; } }
        public static string Icicles { get { return "\uf7ad"; } }
        public static string Igloo { get { return "\uf7ae"; } }
        public static string Mitten { get { return "\uf7b5"; } }
        public static string MugHot { get { return "\uf7b6"; } }
        public static string Radiation { get { return "\uf7b9"; } }
        public static string RadiationAlt { get { return "\uf7ba"; } }
        public static string Restroom { get { return "\uf7bd"; } }
        public static string Satellite { get { return "\uf7bf"; } }
        public static string SatelliteDish { get { return "\uf7c0"; } }
        public static string SdCard { get { return "\uf7c2"; } }
        public static string SimCard { get { return "\uf7c4"; } }
        public static string Skating { get { return "\uf7c5"; } }
        public static string Skiing { get { return "\uf7c9"; } }
        public static string SkiingNordic { get { return "\uf7ca"; } }
        public static string Sleigh { get { return "\uf7cc"; } }
        public static string Sms { get { return "\uf7cd"; } }
        public static string Snowboarding { get { return "\uf7ce"; } }
        public static string Snowman { get { return "\uf7d0"; } }
        public static string Snowplow { get { return "\uf7d2"; } }
        public static string Tenge { get { return "\uf7d7"; } }
        public static string Toilet { get { return "\uf7d8"; } }
        public static string Tools { get { return "\uf7d9"; } }
        public static string Tram { get { return "\uf7da"; } }
        public static string FireAlt { get { return "\uf7e4"; } }
        public static string Bacon { get { return "\uf7e5"; } }
        public static string BookMedical { get { return "\uf7e6"; } }
        public static string BreadSlice { get { return "\uf7ec"; } }
        public static string Cheese { get { return "\uf7ef"; } }
        public static string ClinicMedical { get { return "\uf7f2"; } }
        public static string CommentMedical { get { return "\uf7f5"; } }
        public static string Crutch { get { return "\uf7f7"; } }
        public static string Egg { get { return "\uf7fb"; } }
        public static string Hamburger { get { return "\uf805"; } }
        public static string HandMiddleFinger { get { return "\uf806"; } }
        public static string HardHat { get { return "\uf807"; } }
        public static string Hotdog { get { return "\uf80f"; } }
        public static string IceCream { get { return "\uf810"; } }
        public static string LaptopMedical { get { return "\uf812"; } }
        public static string Pager { get { return "\uf815"; } }
        public static string PepperHot { get { return "\uf816"; } }
        public static string PizzaSlice { get { return "\uf818"; } }
        public static string TrashRestore { get { return "\uf829"; } }
        public static string TrashRestoreAlt { get { return "\uf82a"; } }
        public static string UserNurse { get { return "\uf82f"; } }
        public static string WaveSquare { get { return "\uf83e"; } }
    }
}
